### ISSUE TITLE
Make it run as AWS Lambda

### ISSUE THREAD

**Issue by DarkSmile92** [DarkSmile92/devtoapiparser#1]
### Requirement
One possible improvement would be to make it run as AWS Lambda function with parameters.
### Description
Possible Parameters in relation to their in-script variables should be:
- `APIKEY`->`token`: API-Token *[String]*
- `MY_TAGS`->`tags`: Array of moderated tags *[String-Array]*
- `ONLY_MY_TAGS`->`only_own`: Switch for "just my tags" or "all articles" *[Boolean]*
- `SITES_TO_CHECK`->`sites`: Number of sites to check *[Integer]*

The dependecy for the management is already added ([aws-xray-sdk](https://github.com/aws/aws-xray-sdk-node)).

The output must be redirected from `console.log` to a return value in JSON format.

### Benefits
- Save space on local disk
- Ability to call it from everywhere
- Ability to call it in many different ways (not just console).

### Bonus
- Distinguising between call from Browser and from a client / over request to display the results nicely in a Browser session.

**Comment by chiangs** [comment]
Just a thought on considering Azure Functions over AWS Lambda if we consider future extensibility such as:

- Multiple chained functions to call for updated bad words / phrases resource before completing the search.
- Other functions / apis Dev.to exposes that requires a token.

1. AFs are grouped under an application which means variables such as tokens can be shared across functions.
2. Easier organization as they can be grouped under the DevAPIParser app.

**Comment by DarkSmile92** [comment]
Great idea!
Did not think of them at first. Makes totally sense especially regarding the chained calls.
I'll close this one and open a new one for Azure Functions.
